In [4]:
import pandas as pd
import json
import numpy as np
import requests
from tqdm.auto import tqdm
from config import URL, TOKEN
from datetime import datetime
import urllib3
from dateutil.relativedelta import relativedelta

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

In [10]:
headers = {
    "Authorization": f"Bearer {TOKEN}"
}

start_date = datetime(2017, 1, 1)
today = datetime.now()

all_data = {"entries": []}

current = start_date

while current < today:

    next_month = current + relativedelta(months=1)

    # Do not go beyond today
    month_end = min(next_month, today)

    date_from = current.strftime("%Y%m%d000000")
    date_to = month_end.strftime("%Y%m%d%H%M%S")

    print(f"\nFetching {date_from} -> {date_to}")

    itemCount = np.inf
    offset = 0
    steps = 2000
    progress = None

    while offset < itemCount:

        url = (
            f"{URL}assignment/query?"
            f"filter="
            f"assignmentType:in:24h;spring;first,"
            f"date:gte:{date_from},"
            f"date:lt:{date_to}"
            f"&sort=startDate.timeUtc"
            f"&limit={steps}"
            f"&skip={offset}"
        )

        response = requests.get(
            url,
            headers=headers,
            verify=False
        )

        if response.status_code != 200:
            print(
                f"Error for {date_from} -> {date_to}:",
                response.status_code
            )
            print(response.text)
            break

        responseData = response.json()
        entries = responseData.get("entries", [])

        if progress is None:
            itemCount = responseData["pagingInfo"]["itemCount"]

            progress = tqdm(
                total=itemCount,
                desc=current.strftime("%Y-%m"),
                unit="entries"
            )

        all_data["entries"].extend(entries)

        progress.update(len(entries))

        # Important: avoid infinite loop
        if len(entries) == 0:
            break

        offset += len(entries)

    if progress is not None:
        progress.close()

    current = next_month

Fetching 20170101000000 -> 20170201000000

2017-01:   0%|          | 0/1067 [00:00<?, ?entries/s]

Fetching 20170201000000 -> 20170301000000

2017-02:   0%|          | 0/1054 [00:00<?, ?entries/s]

Fetching 20170301000000 -> 20170401000000

2017-03:   0%|          | 0/1147 [00:00<?, ?entries/s]

Fetching 20170401000000 -> 20170501000000

2017-04:   0%|          | 0/1069 [00:00<?, ?entries/s]

Fetching 20170501000000 -> 20170601000000

2017-05:   0%|          | 0/1166 [00:00<?, ?entries/s]

Fetching 20170601000000 -> 20170701000000

2017-06:   0%|          | 0/1153 [00:00<?, ?entries/s]

Fetching 20170701000000 -> 20170801000000

2017-07:   0%|          | 0/1116 [00:00<?, ?entries/s]

Fetching 20170801000000 -> 20170901000000

2017-08:   0%|          | 0/1269 [00:00<?, ?entries/s]

Fetching 20170901000000 -> 20171001000000

2017-09:   0%|          | 0/1123 [00:00<?, ?entries/s]

Fetching 20171001000000 -> 20171101000000

2017-10:   0%|          | 0/1180 [00:00<?, ?entries/s]

Fetching 20171101000000 -> 20171201000000

2017-11:   0%|          | 0/1253 [00:00<?, ?entries/s]

Fetching 20171201000000 -> 20180101000000

2017-12:   0%|          | 0/1134 [00:00<?, ?entries/s]

Fetching 20180101000000 -> 20180201000000

2018-01:   0%|          | 0/1182 [00:00<?, ?entries/s]

Fetching 20180201000000 -> 20180301000000

2018-02:   0%|          | 0/1141 [00:00<?, ?entries/s]

Fetching 20180301000000 -> 20180401000000

2018-03:   0%|          | 0/1168 [00:00<?, ?entries/s]

Fetching 20180401000000 -> 20180501000000

2018-04:   0%|          | 0/1131 [00:00<?, ?entries/s]

Fetching 20180501000000 -> 20180601000000

2018-05:   0%|          | 0/1291 [00:00<?, ?entries/s]

Fetching 20180601000000 -> 20180701000000

2018-06:   0%|          | 0/1139 [00:00<?, ?entries/s]

Fetching 20180701000000 -> 20180801000000

2018-07:   0%|          | 0/1193 [00:00<?, ?entries/s]

Fetching 20180801000000 -> 20180901000000

2018-08:   0%|          | 0/1251 [00:00<?, ?entries/s]

Fetching 20180901000000 -> 20181001000000

2018-09:   0%|          | 0/1133 [00:00<?, ?entries/s]

Fetching 20181001000000 -> 20181101000000

2018-10:   0%|          | 0/1207 [00:00<?, ?entries/s]

Fetching 20181101000000 -> 20181201000000

2018-11:   0%|          | 0/1205 [00:00<?, ?entries/s]

Fetching 20181201000000 -> 20190101000000

2018-12:   0%|          | 0/1097 [00:00<?, ?entries/s]

Fetching 20190101000000 -> 20190201000000

2019-01:   0%|          | 0/1223 [00:00<?, ?entries/s]

Fetching 20190201000000 -> 20190301000000

2019-02:   0%|          | 0/1140 [00:00<?, ?entries/s]

Fetching 20190301000000 -> 20190401000000

2019-03:   0%|          | 0/1196 [00:00<?, ?entries/s]

Fetching 20190401000000 -> 20190501000000

2019-04:   0%|          | 0/1246 [00:00<?, ?entries/s]

Fetching 20190501000000 -> 20190601000000

2019-05:   0%|          | 0/1271 [00:00<?, ?entries/s]

Fetching 20190601000000 -> 20190701000000

2019-06:   0%|          | 0/1219 [00:00<?, ?entries/s]

Fetching 20190701000000 -> 20190801000000

2019-07:   0%|          | 0/1324 [00:00<?, ?entries/s]

Fetching 20190801000000 -> 20190901000000

2019-08:   0%|          | 0/1326 [00:00<?, ?entries/s]

Fetching 20190901000000 -> 20191001000000

2019-09:   0%|          | 0/1244 [00:00<?, ?entries/s]

Fetching 20191001000000 -> 20191101000000

2019-10:   0%|          | 0/1400 [00:00<?, ?entries/s]

Fetching 20191101000000 -> 20191201000000

2019-11:   0%|          | 0/1294 [00:00<?, ?entries/s]

Fetching 20191201000000 -> 20200101000000

2019-12:   0%|          | 0/1284 [00:00<?, ?entries/s]

Fetching 20200101000000 -> 20200201000000

2020-01:   0%|          | 0/1324 [00:00<?, ?entries/s]

Fetching 20200201000000 -> 20200301000000

2020-02:   0%|          | 0/1305 [00:00<?, ?entries/s]

Fetching 20200301000000 -> 20200401000000

2020-03:   0%|          | 0/1035 [00:00<?, ?entries/s]

Fetching 20200401000000 -> 20200501000000

2020-04:   0%|          | 0/857 [00:00<?, ?entries/s]

Fetching 20200501000000 -> 20200601000000

2020-05:   0%|          | 0/1023 [00:00<?, ?entries/s]

Fetching 20200601000000 -> 20200701000000

2020-06:   0%|          | 0/1035 [00:00<?, ?entries/s]

Fetching 20200701000000 -> 20200801000000

2020-07:   0%|          | 0/1269 [00:00<?, ?entries/s]

Fetching 20200801000000 -> 20200901000000

2020-08:   0%|          | 0/1228 [00:00<?, ?entries/s]

Fetching 20200901000000 -> 20201001000000

2020-09:   0%|          | 0/1342 [00:00<?, ?entries/s]

Fetching 20201001000000 -> 20201101000000

2020-10:   0%|          | 0/1353 [00:00<?, ?entries/s]

Fetching 20201101000000 -> 20201201000000

2020-11:   0%|          | 0/1268 [00:00<?, ?entries/s]

Fetching 20201201000000 -> 20210101000000

2020-12:   0%|          | 0/1279 [00:00<?, ?entries/s]

Fetching 20210101000000 -> 20210201000000

2021-01:   0%|          | 0/1285 [00:00<?, ?entries/s]

Fetching 20210201000000 -> 20210301000000

2021-02:   0%|          | 0/1300 [00:00<?, ?entries/s]

Fetching 20210301000000 -> 20210401000000

2021-03:   0%|          | 0/1382 [00:00<?, ?entries/s]

Fetching 20210401000000 -> 20210501000000

2021-04:   0%|          | 0/1392 [00:00<?, ?entries/s]

Fetching 20210501000000 -> 20210601000000

2021-05:   0%|          | 0/1358 [00:00<?, ?entries/s]

Fetching 20210601000000 -> 20210701000000

2021-06:   0%|          | 0/1493 [00:00<?, ?entries/s]

Fetching 20210701000000 -> 20210801000000

2021-07:   0%|          | 0/1504 [00:00<?, ?entries/s]

Fetching 20210801000000 -> 20210901000000

2021-08:   0%|          | 0/1454 [00:00<?, ?entries/s]

Fetching 20210901000000 -> 20211001000000

2021-09:   0%|          | 0/1492 [00:00<?, ?entries/s]

Fetching 20211001000000 -> 20211101000000

2021-10:   0%|          | 0/1456 [00:00<?, ?entries/s]

Fetching 20211101000000 -> 20211201000000

2021-11:   0%|          | 0/1526 [00:00<?, ?entries/s]

Fetching 20211201000000 -> 20220101000000

2021-12:   0%|          | 0/1522 [00:00<?, ?entries/s]

Fetching 20220101000000 -> 20220201000000

2022-01:   0%|          | 0/1604 [00:00<?, ?entries/s]

Fetching 20220201000000 -> 20220301000000

2022-02:   0%|          | 0/1592 [00:00<?, ?entries/s]

Fetching 20220301000000 -> 20220401000000

2022-03:   0%|          | 0/1779 [00:00<?, ?entries/s]

Fetching 20220401000000 -> 20220501000000

2022-04:   0%|          | 0/1602 [00:00<?, ?entries/s]

Fetching 20220501000000 -> 20220601000000

2022-05:   0%|          | 0/1681 [00:00<?, ?entries/s]

Fetching 20220601000000 -> 20220701000000

2022-06:   0%|          | 0/1698 [00:00<?, ?entries/s]

Fetching 20220701000000 -> 20220801000000

2022-07:   0%|          | 0/1626 [00:00<?, ?entries/s]

Fetching 20220801000000 -> 20220901000000

2022-08:   0%|          | 0/1762 [00:00<?, ?entries/s]

Fetching 20220901000000 -> 20221001000000

2022-09:   0%|          | 0/1788 [00:00<?, ?entries/s]

Fetching 20221001000000 -> 20221101000000

2022-10:   0%|          | 0/1838 [00:00<?, ?entries/s]

Fetching 20221101000000 -> 20221201000000

2022-11:   0%|          | 0/2211 [00:00<?, ?entries/s]

Fetching 20221201000000 -> 20230101000000

2022-12:   0%|          | 0/2156 [00:00<?, ?entries/s]

Fetching 20230101000000 -> 20230201000000

2023-01:   0%|          | 0/2115 [00:00<?, ?entries/s]

Fetching 20230201000000 -> 20230301000000

2023-02:   0%|          | 0/2144 [00:00<?, ?entries/s]

Fetching 20230301000000 -> 20230401000000

2023-03:   0%|          | 0/2318 [00:00<?, ?entries/s]

Fetching 20230401000000 -> 20230501000000

2023-04:   0%|          | 0/2176 [00:00<?, ?entries/s]

Fetching 20230501000000 -> 20230601000000

2023-05:   0%|          | 0/2272 [00:00<?, ?entries/s]

Fetching 20230601000000 -> 20230701000000

2023-06:   0%|          | 0/2286 [00:00<?, ?entries/s]

Fetching 20230701000000 -> 20230801000000

2023-07:   0%|          | 0/2165 [00:00<?, ?entries/s]

Fetching 20230801000000 -> 20230901000000

2023-08:   0%|          | 0/2365 [00:00<?, ?entries/s]

Fetching 20230901000000 -> 20231001000000

2023-09:   0%|          | 0/2136 [00:00<?, ?entries/s]

Fetching 20231001000000 -> 20231101000000

2023-10:   0%|          | 0/2191 [00:00<?, ?entries/s]

Fetching 20231101000000 -> 20231201000000

2023-11:   0%|          | 0/2147 [00:00<?, ?entries/s]

Fetching 20231201000000 -> 20240101000000

2023-12:   0%|          | 0/2035 [00:00<?, ?entries/s]

Fetching 20240101000000 -> 20240201000000

2024-01:   0%|          | 0/2154 [00:00<?, ?entries/s]

Fetching 20240201000000 -> 20240301000000

2024-02:   0%|          | 0/2112 [00:00<?, ?entries/s]

Fetching 20240301000000 -> 20240401000000

2024-03:   0%|          | 0/2132 [00:00<?, ?entries/s]

Fetching 20240401000000 -> 20240501000000

2024-04:   0%|          | 0/2212 [00:00<?, ?entries/s]

Fetching 20240501000000 -> 20240601000000

2024-05:   0%|          | 0/2303 [00:00<?, ?entries/s]

Fetching 20240601000000 -> 20240701000000

2024-06:   0%|          | 0/2087 [00:00<?, ?entries/s]

Fetching 20240701000000 -> 20240801000000

2024-07:   0%|          | 0/2271 [00:00<?, ?entries/s]

Fetching 20240801000000 -> 20240901000000

2024-08:   0%|          | 0/2309 [00:00<?, ?entries/s]

Fetching 20240901000000 -> 20241001000000

2024-09:   0%|          | 0/2367 [00:00<?, ?entries/s]

Fetching 20241001000000 -> 20241101000000

2024-10:   0%|          | 0/2570 [00:00<?, ?entries/s]

Fetching 20241101000000 -> 20241201000000

2024-11:   0%|          | 0/2351 [00:00<?, ?entries/s]

Fetching 20241201000000 -> 20250101000000

2024-12:   0%|          | 0/2304 [00:00<?, ?entries/s]

Fetching 20250101000000 -> 20250201000000

2025-01:   0%|          | 0/2416 [00:00<?, ?entries/s]

Fetching 20250201000000 -> 20250301000000

2025-02:   0%|          | 0/2296 [00:00<?, ?entries/s]

Fetching 20250301000000 -> 20250401000000

2025-03:   0%|          | 0/2277 [00:00<?, ?entries/s]

Fetching 20250401000000 -> 20250501000000

2025-04:   0%|          | 0/2413 [00:00<?, ?entries/s]

Fetching 20250501000000 -> 20250601000000

2025-05:   0%|          | 0/2355 [00:00<?, ?entries/s]

Fetching 20250601000000 -> 20250701000000
Error for 20250601000000 -> 20250701000000: 504


Fetching 20250701000000 -> 20250801000000

2025-07:   0%|          | 0/2535 [00:00<?, ?entries/s]

Fetching 20250801000000 -> 20250901000000

2025-08:   0%|          | 0/2294 [00:00<?, ?entries/s]

Fetching 20250901000000 -> 20251001000000

2025-09:   0%|          | 0/2370 [00:00<?, ?entries/s]

Fetching 20251001000000 -> 20251101000000

2025-10:   0%|          | 0/2409 [00:00<?, ?entries/s]

Fetching 20251101000000 -> 20251201000000

2025-11:   0%|          | 0/2203 [00:00<?, ?entries/s]

Fetching 20251201000000 -> 20260101000000

2025-12:   0%|          | 0/2279 [00:00<?, ?entries/s]

Fetching 20260101000000 -> 20260201000000
Error for 20260101000000 -> 20260201000000: 504


Fetching 20260201000000 -> 20260301000000

2026-02:   0%|          | 0/2157 [00:00<?, ?entries/s]

Fetching 20260301000000 -> 20260401000000

2026-03:   0%|          | 0/2260 [00:00<?, ?entries/s]

Fetching 20260401000000 -> 20260501000000

2026-04:   0%|          | 0/2482 [00:00<?, ?entries/s]

Fetching 20260501000000 -> 20260601000000

2026-05:   0%|          | 0/2330 [00:00<?, ?entries/s]

Fetching 20260601000000 -> 20260701000000

2026-06:   0%|          | 0/2442 [00:00<?, ?entries/s]

Fetching 20260701000000 -> 20260801000000

2026-07:   0%|          | 0/2496 [00:00<?, ?entries/s]

Fetching 20260801000000 -> 20260901000000

2026-08:   0%|          | 0/2362 [00:00<?, ?entries/s]

Fetching 20260901000000 -> 20260901151907

2026-09:   0%|          | 0/1306 [00:00<?, ?entries/s]

In [12]:
exceptions = [
	"metadata",
	"locality",
	"postalcode",
	"contactoptions",
	"personFullName",
	"personFullNameNoTitle",
	"tenantid",
	"persontype",
	"adresse",
	"mailAddressing",
	"socialInsuranceNumber",
	"comments",
	"givenName",
	"familyName",
	"primaryEmailAddress",
	'addresses',
	'primaryPhoneNumber',
	'address',
	'residentialAddress',
	'address',
	'geoLocation',
	'billingAddress',
	'serviceAddress',
	'legalAddress',
	'businessAddress',
	'emailAddresses',
	'phoneNumbers',
	'personFullNameNoTitle',
	'personFullName',
	'mailAddressing',
	'postalAddress',
	'contractualAddressing',
	'caatsDateOfBirth',
	'gender',
	'locations',
	'bankDetails',
	'personStatus',
	"chapterId",
	"language",
	"ordinal",
	"sectionId",
	"academicTitlePrefix",
	"personNr",
	"content",
	"consecutiveNumber",
	'Klient:innen_Empfohlen_Ja',
	'Klient:innen_Erstrkontakt_erfassen_Ja',
	'Klient:innen_Bew_Ein_Ja',
	'abrech-akonto',
	'abrech-buerge-hinterlegt',
	'pers-visite-keine',
	'medizinische-delegation-hochgeladen',
	'medizinische-delegation-nicht-notwendig',
	'Klient:innen_Medizinische_Delegation_Ja',
	'pflegerische-delegation-hochgeladen',
	'pflegerische-delegation-nicht-notwendig',
	'Klient:innen_Pflegerische_Delegation_JA',
	"admin-beruf",
	'pflegevisite-letzte-date',
	'pflegevisite-letzte-dgkp',
	'pflegerisch-person',
	'erstkontakt-bemerkung',
	"admin-kooperationspartner",
	'birthName',
'confessionId',
'confession',
'nationalityId',
'placeOfBirth',
'paymentBlockReason',
'chamberOfCommerceMembershipNr',
'avatarFileId',
'empfohlen-von-category',
'visibilityConditionId',
'deutschkennt-bew-von',
'Kinder_Nein',
'covid-1',
'covid-2',
'covid-3',
'keine-kurse',
'agentur-zuletzt',
'orgRef',
'businesscase',
'comment',
'commentArrival',
'commentDeparture',
'region',
'contactInfo',
'busnessCaseStatus',
'transportOrgArrival',
'transportOrgDeparture',
'assigneeContactInfo',
'assigneeNationality',
'assigneOrgRef',
'assignmentType',
'businessCaseOrgRef',
'businessCaseType',
'assigneeOrgRef',
'hasOrder',
'businessCaseStatus',
"businessCaseStartDate",
"businessCaseEndDate",
"clientAddress",
"region",
"arrivalDate",
"departureDate",
"timeUtc",
"objectKey",
"categoryShortName",
"hasDisplayText",
"displayText",
"objectId",
"objectType",
"cycleLength"
]

exceptions = [x.lower() for x in exceptions]

In [13]:
def extractStatement(statement):
    field = {}
    if statement["statementId"].lower() in exceptions:
        return field

    match statement["answerScheme"]:
        case 1:
            field[statement["statementId"]] = statement["answerValue"]["displayText"]
        case 2:
            #do nothing
            field = {}
        case 3:
            field[statement["statementId"]] = statement["answerYesno"] == 2
        case 4:
            answers = statement["answers"]
            for answer in answers:
                if "isSelected" in answer.keys():
                    field[answer["answerId"]] = answer["isSelected"]
                else:
                    field[answer["answerId"]] = False

        case 5:
            answers = statement["answers"]
            for answer in answers:
                if "isSelected" in answer.keys():
                    field[answer["answerId"]] = answer["isSelected"]
                else:
                    field[answer["answerId"]] = False
        case 8:
            if "answerDateTime" in statement.keys():
                if "userLocalTime" in statement["answerDateTime"].keys():
                    field[statement["statementId"]] = statement["answerDateTime"]["userLocalTime"]
                elif "timeUtc" in statement["answerDateTime"].keys():
                    field[statement["statementId"]] = statement["answerDateTime"]["timeUtc"]
        case _:
            print(f'Found statement: {statement["answerScheme"]} - {statement["statementId"]} -  {statement}')


    return field
        

def returnEntry(entry):
    keys = entry.keys()
    finalFields = {}
    if "statementId" in keys:
        finalFields = finalFields | extractStatement(entry)
    else:
        for key in keys:
            
            if key.lower() in exceptions:
                continue
            
            typing = type(entry[key]).__name__
            match typing:
                case "str":
                    finalFields[key] = entry[key]
                    
                case "int":
                    finalFields[key] = entry[key]

                case "bool":
                    finalFields[key] = entry[key]

                case "float":
                    finalFields[key] = entry[key]
                    
                case "dict":
                    if key == "assignee":
                        finalFields[key] = entry[key]["objectId"]
                        continue
                    if "displayText" in entry[key].keys():
                        finalFields[key] = entry[key]["displayText"]
                        continue
                    if "userLocalTime" in entry[key].keys():
                        finalFields[key] = entry[key]["userLocalTime"]
                        continue
                    if "timeUtc" in entry[key].keys():
                        finalFields[key] = entry[key]["timeUtc"]
                        continue
                    else:
                        finalFields = finalFields | returnEntry(entry[key])
                    
                case "list":
                    if key == "clients":
                        finalFields[key] = entry[key][0]["objectId"]
                    else:
                        for item in entry[key]:
                            if type(item).__name__ == "dict":
                                finalFields = finalFields | returnEntry(item)
                        

                case _:
                    print(typing)


    
    return finalFields

In [18]:
totalData = []

if all_data["entries"] is not None:
    for entry in all_data["entries"]:
        test = returnEntry(entry)
        totalData.append(test)
        
df = pd.DataFrame(totalData)
df.drop_duplicates(inplace=True)

In [19]:
for col in df.columns:
    non_null = df[col].dropna()

    if len(non_null) > 0 and non_null.isin([True, False]).all():
        df[col] = df[col].fillna(False).astype(bool)

bool_cols = df.select_dtypes(include=["bool", "boolean"]).columns

df[bool_cols] = df[bool_cols].fillna(False)


df = df.replace(r'^\s*$', np.nan, regex=True)

df

C:\Users\npozdena\AppData\Local\Temp\ipykernel_2180\826111804.py:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(False).astype(bool)
C:\Users\npozdena\AppData\Local\Temp\ipykernel_2180\826111804.py:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(False).astype(bool)
C:\Users\npozdena\AppData\Local\Temp\ipykernel_2180\826111804.py:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(False).astype(bool)
C:\Users\npozdena\AppData\Local\Temp\ipykernel_2180\826111804.py:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(False).astype(bool)
C:\Users\npozdena\AppData\Local\Temp\ipykernel_2180\826111804.py:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(False).astype(bool)

,id,startDate,endDate,assignee,clients,admin-packet,arrivalSelfOrganized,departureSelfOrganized,arrivalNoBilling,departureNoBilling,isFirstAssignment,billed,template,seriesIndex,assignmentStatus
0,e88cdba8-fdb5-e9fe-635b-5edea54631e1,20160914000000,20170405000000,e44f66ba-7109-798d-a7b6-9b3c7f311967,e66b5fc6-1eb7-e558-8cfa-c21b59627cca,Sonstige,False,False,False,False,False,NaN,NaN,NaN,NaN
1,5b5db4fe-beca-f2a4-466c-46d83ea6837c,20161012000000,20170111000000,76715853-3f04-fb22-4148-56e0c9f99c06,a360b954-c224-9fed-8683-61ba4e96c82d,CD Perle,False,False,False,False,False,NaN,NaN,NaN,NaN
2,a04ab468-fe04-e7c6-f2fd-f9a23bda6a0b,20161025000000,20170110000000,3a128675-bd76-5d3f-08d4-ada5ce463d51,5ce3d5ab-c86e-e2be-f4e3-3e75985e0460,Sonstige,True,True,True,True,False,NaN,NaN,NaN,NaN
3,bc0ae33d-566c-4e19-0984-2dd733df5e35,20161102000000,20170104000000,2bb3d415-9e79-64f0-209a-026b5822455d,6fd526ac-4f30-143a-7f01-c529f01d6dc8,Sonstige,False,False,False,False,False,NaN,NaN,NaN,NaN
4,51519ea1-35ab-003a-29ac-6c404cc3e020,20161115000000,20170104000000,6cb49891-0fd8-3a44-eb29-2aa3e5921989,c90a9bad-6c54-d3c6-2974-3008ab5de4ce,Basis,False,False,False,False,False,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193054,fbe36af9-aa57-7b7d-3438-91154ae11994,20260901000000,20260929000000,1657ed0e-69b1-c099-a06c-ce0e573e43dd,80e9ce37-98a5-556c-1e71-a8721c979554,Premium,False,False,False,False,True,NaN,"2026-CD24-126742, 01.09.2026-...",NaN,NaN
193055,fc7d7a25-ad52-c1f0-934b-3466e0175624,20260901000000,20260915000000,fd03770b-6106-a065-93c5-e9b6e27e2b45,ef6c6131-31a4-e96a-6f25-b06b5540fe51,Basis,False,False,False,False,True,NaN,"2026-CD24-125969, 01.09.2026-...",NaN,NaN
193056,fd1b1146-a402-a216-9c03-4f17fcbb1b9c,20260901000000,20260929000000,d06366dd-636c-aff3-2641-c6351501bf5b,74b0ec81-6225-2ce0-ea79-05e47e87fea0,Basis,False,False,False,False,True,NaN,"2026-CD24-126743, 04.08.2026-...",1.0,NaN
193057,feb792e2-3492-2fec-d06d-59bc241fcad8,20260901000000,20260929000000,ea966ea6-b748-ec4a-c3ce-cfb7c7172b61,941ad204-d86d-2f0c-ed41-2616d4cfa702,Klassik,False,False,False,False,False,NaN,"2018-CD24-122261, 04.08.2026-...",1.0,NaN
193058,ff32d8a2-16a6-1c32-e2dd-567d976bd65c,20260901000000,20260929000000,a68ba2ab-ee75-fcdb-0438-09a6f0ea5ad2,ae4ef19b-547e-2471-90bb-2e731e5cb061,Premium,False,False,False,False,False,NaN,NaN,NaN,NaN

In [20]:
df.isna().sum()[df.isna().sum() > 0]

admin-packet         14123
billed               81983
template            103583
seriesIndex         104156
assignmentStatus    104238
dtype: int64

In [21]:
if "billed" in df.columns and df["billed"].nunique != 2:
	df["billed"] = df["billed"].notna()
if "admin-packet" in df.columns:
	df = pd.get_dummies(df, columns=["admin-packet"], prefix="paket", drop_first=True)

In [22]:
df

,id,startDate,endDate,assignee,clients,arrivalSelfOrganized,departureSelfOrganized,arrivalNoBilling,departureNoBilling,isFirstAssignment,...,paket_Diplomierte Fachkraft,paket_KH-Nachversorgung,paket_Klassik,paket_Kurzzeit-Urlaubsvertetung,paket_Palliativbegleitung,paket_Premium,paket_Sonstige,paket_ZZ_Pflege leicht,paket_ZZ_Pflegerin,paket_ZZ_Standard Plus
0,e88cdba8-fdb5-e9fe-635b-5edea54631e1,20160914000000,20170405000000,e44f66ba-7109-798d-a7b6-9b3c7f311967,e66b5fc6-1eb7-e558-8cfa-c21b59627cca,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1,5b5db4fe-beca-f2a4-466c-46d83ea6837c,20161012000000,20170111000000,76715853-3f04-fb22-4148-56e0c9f99c06,a360b954-c224-9fed-8683-61ba4e96c82d,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,a04ab468-fe04-e7c6-f2fd-f9a23bda6a0b,20161025000000,20170110000000,3a128675-bd76-5d3f-08d4-ada5ce463d51,5ce3d5ab-c86e-e2be-f4e3-3e75985e0460,True,True,True,True,False,...,False,False,False,False,False,False,True,False,False,False
3,bc0ae33d-566c-4e19-0984-2dd733df5e35,20161102000000,20170104000000,2bb3d415-9e79-64f0-209a-026b5822455d,6fd526ac-4f30-143a-7f01-c529f01d6dc8,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,51519ea1-35ab-003a-29ac-6c404cc3e020,20161115000000,20170104000000,6cb49891-0fd8-3a44-eb29-2aa3e5921989,c90a9bad-6c54-d3c6-2974-3008ab5de4ce,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193054,fbe36af9-aa57-7b7d-3438-91154ae11994,20260901000000,20260929000000,1657ed0e-69b1-c099-a06c-ce0e573e43dd,80e9ce37-98a5-556c-1e71-a8721c979554,False,False,False,False,True,...,False,False,False,False,False,True,False,False,False,False
193055,fc7d7a25-ad52-c1f0-934b-3466e0175624,20260901000000,20260915000000,fd03770b-6106-a065-93c5-e9b6e27e2b45,ef6c6131-31a4-e96a-6f25-b06b5540fe51,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
193056,fd1b1146-a402-a216-9c03-4f17fcbb1b9c,20260901000000,20260929000000,d06366dd-636c-aff3-2641-c6351501bf5b,74b0ec81-6225-2ce0-ea79-05e47e87fea0,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
193057,feb792e2-3492-2fec-d06d-59bc241fcad8,20260901000000,20260929000000,ea966ea6-b748-ec4a-c3ce-cfb7c7172b61,941ad204-d86d-2f0c-ed41-2616d4cfa702,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
193058,ff32d8a2-16a6-1c32-e2dd-567d976bd65c,20260901000000,20260929000000,a68ba2ab-ee75-fcdb-0438-09a6f0ea5ad2,ae4ef19b-547e-2471-90bb-2e731e5cb061,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False

In [25]:
protected_cols = ["startDate", "endDate", "assignee", "clients"]

feature_cols = df.columns.drop(protected_cols)

keep_features = feature_cols[
    df[feature_cols].isna().mean() <= 0.10
]

# Keep protected columns + surviving features
df = df[protected_cols + keep_features.tolist()]

df

,startDate,endDate,assignee,clients,id,arrivalSelfOrganized,departureSelfOrganized,arrivalNoBilling,departureNoBilling,isFirstAssignment,...,paket_Diplomierte Fachkraft,paket_KH-Nachversorgung,paket_Klassik,paket_Kurzzeit-Urlaubsvertetung,paket_Palliativbegleitung,paket_Premium,paket_Sonstige,paket_ZZ_Pflege leicht,paket_ZZ_Pflegerin,paket_ZZ_Standard Plus
0,20160914000000,20170405000000,e44f66ba-7109-798d-a7b6-9b3c7f311967,e66b5fc6-1eb7-e558-8cfa-c21b59627cca,e88cdba8-fdb5-e9fe-635b-5edea54631e1,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1,20161012000000,20170111000000,76715853-3f04-fb22-4148-56e0c9f99c06,a360b954-c224-9fed-8683-61ba4e96c82d,5b5db4fe-beca-f2a4-466c-46d83ea6837c,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,20161025000000,20170110000000,3a128675-bd76-5d3f-08d4-ada5ce463d51,5ce3d5ab-c86e-e2be-f4e3-3e75985e0460,a04ab468-fe04-e7c6-f2fd-f9a23bda6a0b,True,True,True,True,False,...,False,False,False,False,False,False,True,False,False,False
3,20161102000000,20170104000000,2bb3d415-9e79-64f0-209a-026b5822455d,6fd526ac-4f30-143a-7f01-c529f01d6dc8,bc0ae33d-566c-4e19-0984-2dd733df5e35,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,20161115000000,20170104000000,6cb49891-0fd8-3a44-eb29-2aa3e5921989,c90a9bad-6c54-d3c6-2974-3008ab5de4ce,51519ea1-35ab-003a-29ac-6c404cc3e020,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193054,20260901000000,20260929000000,1657ed0e-69b1-c099-a06c-ce0e573e43dd,80e9ce37-98a5-556c-1e71-a8721c979554,fbe36af9-aa57-7b7d-3438-91154ae11994,False,False,False,False,True,...,False,False,False,False,False,True,False,False,False,False
193055,20260901000000,20260915000000,fd03770b-6106-a065-93c5-e9b6e27e2b45,ef6c6131-31a4-e96a-6f25-b06b5540fe51,fc7d7a25-ad52-c1f0-934b-3466e0175624,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
193056,20260901000000,20260929000000,d06366dd-636c-aff3-2641-c6351501bf5b,74b0ec81-6225-2ce0-ea79-05e47e87fea0,fd1b1146-a402-a216-9c03-4f17fcbb1b9c,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
193057,20260901000000,20260929000000,ea966ea6-b748-ec4a-c3ce-cfb7c7172b61,941ad204-d86d-2f0c-ed41-2616d4cfa702,feb792e2-3492-2fec-d06d-59bc241fcad8,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
193058,20260901000000,20260929000000,a68ba2ab-ee75-fcdb-0438-09a6f0ea5ad2,ae4ef19b-547e-2471-90bb-2e731e5cb061,ff32d8a2-16a6-1c32-e2dd-567d976bd65c,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False

In [29]:
df.to_csv("assignments.csv", sep=";", index=False)